// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAy-IIB7vGCVirJjSrqb4Y3R2IiSq_O2f8',
    appId: '1:343641735550:web:1c1e948acb2a537204f32f',
    messagingSenderId: '343641735550',
    projectId: 'utsmobile-983bd',
    authDomain: 'utsmobile-983bd.firebaseapp.com',
    storageBucket: 'utsmobile-983bd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxlc0l7UIUvQfFls9qPxKodTBEeyFRjTI',
    appId: '1:343641735550:android:7aef12b9b71e712e04f32f',
    messagingSenderId: '343641735550',
    projectId: 'utsmobile-983bd',
    storageBucket: 'utsmobile-983bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBtNhcxuGaH5lj8xAD3lXeMhwzJ_nwvHI',
    appId: '1:343641735550:ios:e249df2476a2adcb04f32f',
    messagingSenderId: '343641735550',
    projectId: 'utsmobile-983bd',
    storageBucket: 'utsmobile-983bd.firebasestorage.app',
    iosBundleId: 'com.example.utsmobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBtNhcxuGaH5lj8xAD3lXeMhwzJ_nwvHI',
    appId: '1:343641735550:ios:e249df2476a2adcb04f32f',
    messagingSenderId: '343641735550',
    projectId: 'utsmobile-983bd',
    storageBucket: 'utsmobile-983bd.firebasestorage.app',
    iosBundleId: 'com.example.utsmobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAy-IIB7vGCVirJjSrqb4Y3R2IiSq_O2f8',
    appId: '1:343641735550:web:1abc07fd4bb1932e04f32f',
    messagingSenderId: '343641735550',
    projectId: 'utsmobile-983bd',
    authDomain: 'utsmobile-983bd.firebaseapp.com',
    storageBucket: 'utsmobile-983bd.firebasestorage.app',
  );

}